steps:
# Step 1: Install Dependencies, Create Bundle, Fix Permissions, and Build the App
- name: 'reactnativecommunity/react-native-android'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e
      echo "=== Installing Dependencies ==="
      npm install --legacy-peer-deps

      echo "=== Creating React Native Bundle ==="
      mkdir -p android/app/src/main/assets
      npx react-native bundle \
        --platform android \
        --dev false \
        --entry-file index.js \
        --bundle-output android/app/src/main/assets/index.android.bundle \
        --assets-dest android/app/src/main/res

      echo "=== Building APK ==="
      cd android

      echo "=== Using Gradle directly ==="
      gradle clean assembleRelease --no-daemon --stacktrace

# Step 2: Distribute the APK to testers via Firebase App Distribution.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'firebase'
    - 'appdistribution:distribute'
    - 'android/app/build/outputs/apk/release/app-release.apk'
    - '--app=1:53700756169:android:2f4d0891542f2c286d51d8'
    - '--release-notes=This build is successful. The pipeline is now fully operational.'
    - '--groups=testers'

# Make the generated APK available as a downloadable artifact.
artifacts:
  objects:
    location: 'gs://memory-lane-app-469523-builds'
    paths: ['android/app/build/outputs/apk/release/app-release.apk']

# Set a generous timeout for the build.
timeout: 3600s
