steps:
  # Install Node.js dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '--legacy-peer-deps']
    dir: '.'

  # Create React Native bundle
  - name: 'node:20'
    entrypoint: 'npx'
    args:
      - 'react-native'
      - 'bundle'
      - '--platform'
      - 'android'
      - '--dev'
      - 'false'
      - '--entry-file'
      - 'index.js'
      - '--bundle-output'
      - 'android/app/src/main/assets/index.android.bundle'
      - '--assets-dest'
      - 'android/app/src/main/res'
    dir: '.'

  # Build APK using official Android builder
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '--rm'
      - '-v'
      - '/workspace:/workspace'
      - '-w'
      - '/workspace'
      - 'cimg/android:2024.01.1'
      - 'bash'
      - '-c'
      - |
        export ANDROID_HOME=/home/circleci/android-sdk
        export ANDROID_SDK_ROOT=/home/circleci/android-sdk
        cd android

        # Fix line endings for Windows-created files
        sed -i 's/\r$//' gradlew
        chmod +x gradlew

        # Build the APK
        ./gradlew assembleRelease --no-daemon --stacktrace

        # List generated APK files
        find . -name "*.apk" -type f

# Store the APK as build artifact
artifacts:
  objects:
    location: 'gs://memory-lane-app-469523-builds-1758588886'
    paths: ['android/app/build/outputs/apk/release/*.apk']

timeout: 1800s