steps:
  # Install Node.js dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '--legacy-peer-deps', '--force']
    dir: '.'

  # Install Expo CLI
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '-g', '@expo/cli', 'eas-cli']
    dir: '.'

  # Create bundle only (skip APK build for now)
  - name: 'node:20'
    entrypoint: 'npx'
    args:
      - 'react-native'
      - 'bundle'
      - '--platform'
      - 'android'
      - '--dev'
      - 'false'
      - '--entry-file'
      - 'index.js'
      - '--bundle-output'
      - 'LegacyHonored.bundle'
      - '--assets-dest'
      - 'assets'
    dir: '.'

# Store the bundle for now
artifacts:
  objects:
    location: 'gs://memory-lane-app-469523-builds-1758253577'
    paths: ['LegacyHonored.bundle', 'assets/**/*']

timeout: 1200s