steps:
# Step 1: Build a comprehensive Android build environment with Node.js
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/react-native-android-builder', '.', '-f', 'Dockerfile.optimized']

# Step 2: Install dependencies and build the React Native bundle
- name: 'gcr.io/$PROJECT_ID/react-native-android-builder'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e
      echo "=== Installing Node.js dependencies ==="
      npm install --legacy-peer-deps

      echo "=== Creating React Native bundle ==="
      mkdir -p android/app/src/main/assets
      npx react-native bundle \
        --platform android \
        --dev false \
        --entry-file index.js \
        --bundle-output android/app/src/main/assets/index.android.bundle \
        --assets-dest android/app/src/main/res

# Step 3: Build the signed release APK
- name: 'gcr.io/$PROJECT_ID/react-native-android-builder'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e
      cd android

      echo "=== Gradle Wrapper Permissions ==="
      chmod +x gradlew

      echo "=== Building Release APK ==="
      ./gradlew assembleRelease --no-daemon --stacktrace --info

      echo "=== Verifying APK Build ==="
      find . -name "*.apk" -type f -exec ls -la {} \;

# Step 4: Install Firebase CLI and distribute APK
- name: 'node:20'
  entrypoint: 'bash'
  env:
    - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/firebase-service-account.json'
  secretEnv: ['FIREBASE_TOKEN']
  args:
    - '-c'
    - |
      set -e

      echo "=== Installing Firebase CLI ==="
      npm install -g firebase-tools

      echo "=== Firebase App Distribution ==="
      firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
        --app "1:53700756169:android:2f4d0891542f2c286d51d8" \
        --release-notes "Automated release build from Google Cloud Build - $(date)" \
        --groups "testers" \
        --token "$FIREBASE_TOKEN"

# Store build artifacts
artifacts:
  objects:
    location: 'gs://memory-lane-app-469523-builds'
    paths:
      - 'android/app/build/outputs/apk/release/*.apk'
      - 'android/app/build/outputs/mapping/release/mapping.txt'

# Store the custom builder image
images:
  - 'gcr.io/$PROJECT_ID/react-native-android-builder'

# Configure secrets
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/firebase-token/versions/latest
    env: 'FIREBASE_TOKEN'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

timeout: 3600s