steps:
  # Build unsigned APK using React Native CLI
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'run'
      - '--rm'
      - '-v'
      - '/workspace:/workspace'
      - '-w'
      - '/workspace'
      - 'reactnativecommunity/react-native-android:14.0'
      - 'bash'
      - '-c'
      - |
        # Install dependencies
        npm install --legacy-peer-deps

        # Create bundle
        npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

        # Build debug APK (easier than release)
        cd android
        ./gradlew assembleDebug --no-daemon

        # List generated files
        find . -name "*.apk" -type f

# Store any APK files that were created
artifacts:
  objects:
    location: 'gs://memory-lane-app-469523-builds-1758588886'
    paths: ['android/app/build/outputs/apk/debug/*.apk']

timeout: 1800s