steps:
  # Install dependencies and create bundle
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install --legacy-peer-deps --force
        mkdir -p android/app/src/main/assets
        npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

  # Simple APK build with minimal environment
  - name: 'openjdk:11-jdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y wget unzip
        cd /tmp
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p /opt/android-sdk/cmdline-tools
        mv cmdline-tools /opt/android-sdk/cmdline-tools/latest
        export ANDROID_HOME=/opt/android-sdk
        /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=/opt/android-sdk <<< 'y'
        /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0" --sdk_root=/opt/android-sdk
        cd /workspace/android
        bash ./gradlew assembleRelease --no-daemon
        find . -name "*.apk" -type f

artifacts:
  objects:
    location: 'gs://memory-lane-app-469523-builds-1758253577'
    paths: ['android/app/build/outputs/apk/release/*.apk']

timeout: 2400s