steps:
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '--legacy-peer-deps', '--force']

  - name: 'node:20'
    entrypoint: 'npx'
    args:
      - 'react-native'
      - 'bundle'
      - '--platform'
      - 'android'
      - '--dev'
      - 'false'
      - '--entry-file'
      - 'index.js'
      - '--bundle-output'
      - 'android/app/src/main/assets/index.android.bundle'
      - '--assets-dest'
      - 'android/app/src/main/res'

  - name: 'node:20'
    entrypoint: 'mkdir'
    args: ['-p', 'android/app/src/main/assets']

  - name: 'cimg/android:2023.08'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        export ANDROID_HOME=/home/circleci/android-sdk
        export ANDROID_SDK_ROOT=/home/circleci/android-sdk
        cd android
        chmod +x gradlew
        ./gradlew assembleRelease --no-daemon --stacktrace
        find . -name "*.apk" -type f

artifacts:
  objects:
    location: 'gs://memory-lane-app-469523-builds-1758253577'
    paths: ['android/app/build/outputs/apk/release/*.apk']

timeout: 1800s