steps:
  # Install Node.js dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '--legacy-peer-deps']
    dir: '.'

  # Create assets directory
  - name: 'alpine'
    entrypoint: 'mkdir'
    args: ['-p', 'android/app/src/main/assets']

  # Create JavaScript bundle
  - name: 'node:20'
    entrypoint: 'npx'
    args:
      - 'react-native'
      - 'bundle'
      - '--platform'
      - 'android'
      - '--dev'
      - 'false'
      - '--entry-file'
      - 'index.js'
      - '--bundle-output'
      - 'android/app/src/main/assets/index.android.bundle'
      - '--assets-dest'
      - 'android/app/src/main/res'
    dir: '.'

  # Build Android APK
  - name: 'cimg/android:2023.07'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd android
        sudo chmod +x gradlew
        sudo ./gradlew assembleRelease --no-daemon

# Store the APK as build artifact
artifacts:
  objects:
    location: 'gs://memory-lane-app-469523-builds'
    paths: ['android/app/build/outputs/apk/release/*.apk']

timeout: 1200s